language: java
jdk:
  - oraclejdk8
sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.21.2

cache:
  directories:
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/jars-2
    - $HOME/.gradle/caches/jars-3
    - $HOME/.gradle/caches/modules-2/files-2.1/
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

before_install:
  - mkdir -p "$HOME/bin";
  - export PATH="$PATH:$HOME/bin";
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > "$HOME/bin/docker-compose";
  - chmod +x "$HOME/bin/docker-compose";
script:
  - ./gradlew check
  - cd src/integrationTest/docker
  - sudo docker-compose up -d zookeeper-1 kafka-1 schema-registry-1 && sleep 30 && sudo docker-compose run --rm integration-test
  - sudo docker-compose down
  - cd ../../..
after_script:
  - ./gradlew sendCoverageToCodacy

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file:
    - build/libs/*.jar
    - build/distributions/*.zip
    - build/distributions/*.tar.gz
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - ./gradlew bintrayUpload
